mag7_intel:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: "/Users/eunicetan/Desktop/eunice-bde-dd6fa2fdd0cc.json"
      project: "eunice-bde"
      dataset: "mag7_intel_staging"
      location: "US"
      threads: 4
      priority: interactive
      timeout_seconds: 300